name: virtual-copernicus-env
channels:
  - conda-forge
  - anaconda
dependencies:
  - python
  - netcdf4=1.4.2
  - matplotlib
  - basemap
  - scipy
  - xarray
  - pandas
  - numpy
  - seaborn
  - pip:
    - motuclient>=1.8.1
    - cdo>=1.4.0
    - julia
