name: virtual-copernicus-env
channels:
  - conda-forge
  - anaconda
  - conda-forge/label/gcc7
dependencies:
  - python
  - r-irkernel=0.8.11
  - nco=4.7.7
  - pynco=0.0.4
  - netcdf-fortran=4.4.4
  - netcdf4=1.4.2
  - libnetcdf=4.6.1
  - matplotlib
  - basemap
  - scipy
  - xarray
  - pandas
  - numpy
  - seaborn
  - pip:
    - motuclient>=1.8.1
    - cdo>=1.4.0
    - julia
